<a href="https://colab.research.google.com/github/kk412027247/nlp/blob/main/mean_polling_and_max_polling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

# 输入数据 (batch_size=2, sequence_length=3, features=2)
inputs = tf.constant([
    [[1, 2], [3, 4], [5, 6]],   # 样本1
    [[7, 8], [9, 10], [11, 12]] # 样本2
], dtype=tf.float32)

print(inputs.shape)

(2, 3, 2)


In [ ]:
# 沿时间步维度（axis=1）计算均值
mean_output = tf.reduce_mean(inputs, axis=1)

"""
输出：
[[3. 4.]  # (1+3+5)/3=3, (2+4+6)/3=4
 [9. 10.]] # (7+9+11)/3=9, (8+10+12)/3=10
"""

print(mean_output)
print(mean_output.shape)

tf.Tensor(
[[ 3.  4.]
 [ 9. 10.]], shape=(2, 2), dtype=float32)
(2, 2)


In [ ]:
from tensorflow.keras.layers import GlobalMaxPooling1D

# 创建池化层
max_pool = GlobalMaxPooling1D()
max_output = max_pool(inputs)
"""
输出：
[[5. 6.]   # max(1,3,5)=5, max(2,4,6)=6
 [11. 12.]] # max(7,9,11)=11, max(8,10,12)=12
"""

print(max_output)
print(max_output.shape)

tf.Tensor(
[[ 5.  6.]
 [11. 12.]], shape=(2, 2), dtype=float32)
(2, 2)
